# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
php-version = "8.4.0"

[source]
paths = ["app/", "database/factories/", "database/seeders/", "tests/"]
includes = [
    "vendor/laravel/framework/src/Illuminate",
    "vendor/pestphp/pest/src",
]
excludes = ["vendor"]

[formatter]
print-width = 120
tab-width = 4
use-tabs = false
end-of-line = "lf"
classlike-brace-style = "same_line"
method-brace-style = "same_line"

[linter]
baseline = "linter-baseline.toml"
integrations = ["laravel", "pest"]
excludes = []


[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
halstead = { effort-threshold = 7000 }
no-literal-password = { enabled = false }
class-name = { enabled = false }

[analyzer]
baseline = "analyzer-baseline.toml"
find-unused-definitions = true
find-unused-expressions = false
analyze-dead-code = false
check-throws = true
allow-possibly-undefined-array-keys = true
perform-heuristic-checks = true
existence-issues = false

[guard]
excludes = []

[guard.perimeter.layers]
laravel = ["Illuminate\\**"]
pest = ["Pest\\**"]
testing = ["PHPUnit\\**"]

[[guard.perimeter.rules]]
namespace = "App\\"
permit = ["@native", "@self", "@layer:laravel"]

[[guard.perimeter.rules]]
namespace = "Database\\Factories\\"
permit = ["@native", "@self", "@layer:laravel", "App\\Models\\**"]

[[guard.perimeter.rules]]
namespace = "Database\\Seeders\\"
permit = ["@native", "@self", "@layer:laravel", "App\\Models\\**"]

[[guard.perimeter.rules]]
namespace = "Tests\\"
permit = ["@all"]

[[guard.perimeter.rules]]
namespace = "@global"
permit = ["@all"]
